externalURL: http://harbor.local

harborAdminPassword: "Harbor12345"

expose:
  type: nodePort
  tls:
    enabled: false
  nodePort:
    name: harbor
    ports:
      http:
        nodePort: 30002
      https:
        nodePort: 30003

notary:
  enabled: false

trivy:
  enabled: false

gc:
  enabled: true
  schedule: "0 2 * * *"