replicaCount: 1

image:
  repository: 10.0.2.15:30002/helm-practice-cicdk3slab/hello-app
  pullPolicy: Always
  tag: "de3e101"

service:
  type: ClusterIP
  port: 5000

imagePullSecrets:
  - name: harbor-cred