apiVersion: v1
kind: Secret
metadata:
  name: my-custom-secret
type: Opaque
data:
  mariadb-password: {{ "cok-gizli-sifrem-123" | b64enc | quote }}
  
  wordpress-password: {{ "admin-123" | b64enc | quote }}