- name: Sistem Hazırlığı 
  hosts: k3s_nodes
  become: yes
  tasks:
    - name: DNS ayarlarını 8.8.8.8 olarak sabitle
      shell: |
        rm -f /etc/resolv.conf
        echo "nameserver 8.8.8.8" > /etc/resolv.conf
        echo "nameserver 1.1.1.1" >> /etc/resolv.conf
      tags: dns_fix

    - name: Internet bağlantısını test et (Google'a ping)
      command: ping -c 1 google.com
      register: ping_result
      ignore_errors: yes

    - name: Paket listesini güncelle
      apt:
        name:
          - curl
          - wget
          - git
          - htop
          - docker.io
          - apt-transport-https
          - gpg
        state: present
        update_cache: yes
    - name: Paket listesini güncelle ve gerekli araçları kur
      apt:
        name:
          - curl
          - wget
          - git
          - htop
          - docker.io  
        state: present
        update_cache: yes

    - name: Docker servisini başlat ve enable et
      service:
        name: docker
        state: started
        enabled: yes

    - name: Helm kurulum scriptini indir ve çalıştır
      shell: |
        curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
        chmod 700 get_helm.sh
        ./get_helm.sh
      args:
        creates: /usr/local/bin/helm
      environment:
        PATH: "/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

    - name: Helm kurulumunu doğrula
      command: helm version
      register: helm_version_output
      changed_when: false

    - name: Helm versiyonunu ekrana yaz
      debug:
        msg: "Helm Başarıyla Kuruldu: {{ helm_version_output.stdout }}"

