name: Build and Deploy Hello App

on:
  push:
    branches: ["main"]
    paths:
      - "src/hello-world-app/**"
      - "hello-app/**"

jobs:
  build-push-deploy:
    runs-on: helm-practice-cicd
    permissions:
      contents: write

    env:
      REGISTRY: 10.0.2.15:30002
      PROJECT: helm-practice-cicdk3slab
      IMAGE_NAME: hello-app

    steps:
      - name: Kodu Çek (Checkout)
        uses: actions/checkout@v3

      - name: Kısa SHA Oluştur (Versiyonlama için)
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV


      - name: Docker Login (Harbor - NodePort)
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" \
            | docker login 10.0.2.15:30002 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          set -euo pipefail

          IMAGE_TAG="10.0.2.15:30002/helm-practice-cicdk3slab/hello-app:${{ env.SHORT_SHA }}"
          echo "IMAGE_TAG=$IMAGE_TAG"

          cd src/hello-world-app
          docker build -t "$IMAGE_TAG" .
          docker push "$IMAGE_TAG"

          echo "Image pushed: $IMAGE_TAG"

      - name: Helm values tag güncelle (GitOps)
        run: |
          set -euo pipefail

          # hello-app/values.yaml içinde "tag:" satırını güncelle
          # tag: "xxx" veya tag: xxx fark etmez
          sed -i -E 's/^([[:space:]]*tag:[[:space:]]*).*/\1"'${{ env.SHORT_SHA }}'"/' hello-app/values.yaml

          echo "Updated values.yaml:"
          grep -nE '^[[:space:]]*tag:' hello-app/values.yaml

      - name: Değişikliği GitHub'a Geri Yolla
        run: |
          set -euo pipefail

          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"

          git add hello-app/values.yaml

          # Değişiklik yoksa commit atma
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "ci: update hello-app image tag to ${{ env.SHORT_SHA }}"
          git push
