name: K3s Autoscale Test
on: [push, workflow_dispatch]

jobs:
  test-job-1:
    runs-on: helm-practice-cicd
    steps:
      - name: Kimim ben?
        run: |
          echo "Merhaba! Ben K3s icinde calisan gecici bir runnerim."
          hostname
      - name: Yük Simülasyonu (Bekle)
        run: sleep 30

  test-job-2:
    runs-on: helm-practice-cicd
    needs: test-job-1
    steps:
      - name: İkinci İş
        run: echo "Ben de ikinci runnerim!"
      - name: Bekle
        run: sleep 20